baseURL = 'https://kazumbah.com.au/'
languageCode = 'en-au'
title = 'Kazumbah Zumba with Kaz in Murwillumbah'
theme = 'mytheme'

[params]
  owner = 'Kaz Chapman'
  phone = '0422 233 836'
  phoneE164 = '+61-422-233-836'
  facebook = 'https://www.facebook.com/p/Kazumbah-Murwillumbah-Zumba-with-Kaz-100057742846960/'
  business = 'Kazumbah – Zumba with Kaz'
  serviceAreas = 'Murwillumbah & Banora Point'
  areas = ['Murwillumbah NSW', 'Banora Point NSW', 'Tweed Shire']
  mapEmbed = 'https://www.google.com/maps?q=Murwillumbah%20NSW&output=embed'
